/* Opportunity Intelligence cockpit. Uses canonical data services; does not recalculate SmartScore. */
(function(window){'use strict';
const D=window.KHATER_DATA||{},F=D.funds,M=D.macro,MI=D.macroIntelligence;
if(!F)throw new Error('opportunity-layer.js requires funds-service.js');
const $=id=>document.getElementById(id),esc=D.escape||((s)=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c])));
const fmt=n=>n==null?'—':Number(n).toLocaleString('en-US',{maximumFractionDigits:2}),pct=n=>n==null?'—':fmt(n)+'%',LABEL={weekly:'أسبوع','4weeks':'4 أسابيع',ytd:'منذ بداية العام',last12m:'12 شهرًا','1y':'سنة','2y':'سنتان','3y':'3 سنوات','4y':'4 سنوات','5y':'5 سنوات','6y':'6 سنوات'};
let universe=null,lastHorizon='last12m';
function confidence(x){const s=String(x||'').toLowerCase();return s.includes('high')||x>=90?'مرتفعة':s.includes('moderate')||x>=70?'متوسطة':s.includes('limited')?'محدودة':'غير كافية'}
function regimeFit(cat,regime){const c=String(cat||'').toLowerCase(),k=regime?.key;const has=(...xs)=>xs.some(x=>c.includes(x));if(k==='inflation-hedge'){if(has('gold','ذهب','دولار','usd','currency'))return{score:18,label:'ملاءمة مرتفعة',reason:'السياق الحالي يركز على حماية القوة الشرائية وأثر سعر الصرف.'};if(has('fixed','income','دخل ثابت','نقد','cash','money'))return{score:3,label:'ملاءمة محدودة',reason:'العائد الاسمي يحتاج مقارنة مباشرة مع التضخم وسعر الصرف.'};return{score:0,label:'محايدة',reason:'تحتاج الفئة إلى إثبات تفوقها بعد أثر التضخم والعملـة.'}}
if(k==='carry'){if(has('fixed','income','دخل ثابت','نقد','cash','money','bond','سند','أذون','tbill'))return{score:18,label:'ملاءمة مرتفعة',reason:'العائد النقدي المرتفع يرفع معيار المقارنة قبل تحمل مخاطرة إضافية.'};if(has('equity','أسهم','stock','growth'))return{score:2,label:'ملاءمة مشروطة',reason:'المخاطرة الإضافية يجب أن تبررها زيادة واضحة فوق العائد النقدي.'};return{score:0,label:'محايدة',reason:'لا توجد أفضلية سياقية كافية بعد.'}}
if(k==='mixed-risk-on'){if(has('equity','أسهم','stock','growth','egypt','egx'))return{score:14,label:'ملاءمة مرتفعة',reason:'صعود الأصول المحلية يجعل فئات المخاطرة جديرة بالفحص، مع اختبار التفوق على المرجع.'};if(has('gold','ذهب'))return{score:4,label:'ملاءمة مشروطة',reason:'الذهب يتحرك أيضًا، لكن يجب فصل أثر العملة عن أداء الأصل.'};return{score:0,label:'محايدة',reason:'لا توجد أفضلية سياقية كافية بعد.'}}
return{score:0,label:'محايدة',reason:'السياق غير حاسم؛ القرار يجب أن يعتمد أكثر على الدليل والمرجع.'}}
function signal(f,rank,catTop,fit){const flags=[];if(f.score!=null&&f.score>=75)flags.push('SmartScore قوي');if(f.ret!=null&&rank<=3)flags.push('عائد متقدم');if(f.ret!=null&&catTop)flags.push('متصدر فئته');if(confidence(f.confidence)==='مرتفعة')flags.push('ثقة مرتفعة');if(fit?.score>=14)flags.push('ملاءمة للسياق');return flags.slice(0,3)}
function model(rows,regime){const valid=rows.filter(f=>f.ret!=null),catMax={};valid.forEach(f=>{catMax[f.cat]=Math.max(catMax[f.cat]??-Infinity,f.ret)});const enriched=valid.map(f=>{const fit=regimeFit(f.cat,regime),conf=confidence(f.confidence),quality=conf==='مرتفعة'?8:conf==='متوسطة'?4:conf==='محدودة'?-6:-12;const score=(f.score??0)*0.55+Math.min(Math.max(f.ret??-100,-100),100)*0.2+fit.score+quality;return{...f,fit,radarScore:score,confidenceLabel:conf}});const ranked=[...enriched].sort((a,b)=>b.radarScore-a.radarScore),leaders=ranked.slice(0,6).map((f,i)=>({...f,rank:i+1,catLeader:f.ret===catMax[f.cat],flags:signal(f,i+1,f.ret===catMax[f.cat],f.fit)}));const qualified=enriched.filter(f=>f.score!=null&&f.score>=75&&['high','moderate'].includes(String(f.confidence||'').toLowerCase())).sort((a,b)=>(b.radarScore-a.radarScore)).slice(0,5);const categories=Object.entries(valid.reduce((m,f)=>{const x=m[f.cat]||(m[f.cat]={cat:f.cat,count:0,avg:null,best:null,fit:null});x.count++;x.avg=(x.avg==null?f.ret:(x.avg*(x.count-1)+f.ret)/x.count);x.fit=regimeFit(f.cat,regime);if(!x.best||f.ret>x.best.ret)x.best=f;return m},{})).map(([,x])=>({...x,radarScore:(x.avg??0)*0.25+(x.fit?.score||0)+(x.count>=3?3:0)})).sort((a,b)=>b.radarScore-a.radarScore);return{leaders,qualified,categories,validCount:valid.length}}
function render(rows,regime){const host=$('opportunityLayer');if(!host)return;const m=model(rows,regime),regimeTitle=regime?.title||'السوق تحت المراقبة';const leader=m.leaders[0];host.innerHTML='<div class="opp-head"><div><div class="opp-kicker">OPPORTUNITY RADAR</div><h2>من السياق الاقتصادي إلى منطقة تستحق التحقيق</h2><p>الترتيب هنا ليس ترتيب عائد خام: يوازن SmartScore مع العائد، جودة البيانات، وملاءمة الفئة لنظام السوق الحالي. لا توجد توصية آلية بالشراء.</p></div><div class="opp-regime"><span>حالة السوق</span><b>'+esc(regimeTitle)+'</b><small>الرادار مرتبط بنفس Macro Intelligence</small></div></div><div class="opp-grid"><article class="opp-card hero"><span>أقوى منطقة للفحص</span><strong>'+esc(leader?.name||'—')+'</strong><b>'+pct(leader?.ret)+'</b><small>'+esc(leader?.cat||'—')+' · '+esc(leader?.fit?.label||'محايدة')+' · '+(leader?.score==null?'غير مقيم':'SmartScore '+fmt(leader.score))+'</small><div>'+signal(leader||{},1,!!leader?.catLeader,leader?.fit).map(x=>'<i>'+esc(x)+'</i>').join('')+'</div><p>'+esc(leader?.fit?.reason||'لا توجد أفضلية سياقية كافية بعد.')+'</p></article><article class="opp-card"><span>فرص مؤهلة للفحص</span><strong>'+m.qualified.length+'</strong><small>SmartScore ≥ 75 + ثقة ليست محدودة</small><div class="mini-list">'+m.qualified.slice(0,3).map(f=>'<a href="fund.html?id='+encodeURIComponent(f.id)+'&h='+encodeURIComponent(lastHorizon)+'"><b>'+esc(f.name)+'</b><em>'+fmt(f.score)+' · '+pct(f.ret)+' · '+esc(f.fit.label)+'</em></a>').join('')+'</div></article><article class="opp-card"><span>أقوى مناطق البحث</span><strong>'+m.categories.length+'</strong><small>ملاءمة السياق + الدليل المتاح، لا العائد وحده</small><div class="mini-list">'+m.categories.slice(0,3).map(x=>'<a href="categories.html"><b>'+esc(x.cat)+'</b><em>'+esc(x.fit?.label||'محايدة')+' · '+pct(x.avg)+' · '+x.count+' صندوق</em></a>').join('')+'</div></article></div><div class="opp-leaders"><div class="leaders-head"><b>Investigation shortlist · ما يستحق التحقق</b><span>'+m.validCount+' صندوقًا له عائد رسمي في '+esc(LABEL[lastHorizon]||lastHorizon)+'</span></div><div class="leader-strip">'+m.leaders.map(f=>'<a class="leader" href="fund.html?id='+encodeURIComponent(f.id)+'&h='+encodeURIComponent(lastHorizon)+'"><small>#'+String(f.rank).padStart(2,'0')+'</small><b>'+esc(f.name)+'</b><span>'+pct(f.ret)+'</span><em>'+esc(f.cat)+' · '+esc(f.fit.label)+'</em><div>'+f.flags.map(x=>'<i>'+esc(x)+'</i>').join('')+'</div></a>').join('')+'</div></div><div class="opp-foot"><b>قاعدة القرار</b><span>السياق يحدد أين نبحث · العائد يجذب الانتباه · SmartScore يختبر الجودة · Benchmark يختبر التفوق · الثقة تحذر · Fund DNA يتحقق.</span></div>'}
async function refresh(){try{if(!universe)universe=await F.getUniverse();const h=document.getElementById('h')?.value||lastHorizon;lastHorizon=h;const p=await F.getPerformanceSnapshot(h),rows=universe.list.map(f=>({...f,ret:p.map[f.id]??null,returnDate:p.returnDates[f.id]??null}));let regime=null;if(M&&MI){try{const md=await M.getAll();regime=MI.regime(md)}catch(e){regime=null}}render(rows,regime)}catch(e){const host=$('opportunityLayer');if(host)host.innerHTML='<div class="opportunity-error">تعذر بناء Opportunity Radar دون المساس بعرض البيانات الرسمي.<br><small>'+esc(e.message)+'</small></div>'}}
function boot(){refresh();const h=$('h');if(h)h.addEventListener('change',refresh)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})(window);