const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\\':'&#39;'}[c]));
/* Platform numeric identity: RTL UI, Latin financial digits 0-9. */
const fmt=(n,d=1)=>Number.isFinite(Number(n))?Number(n).toLocaleString('en-US',{minimumFractionDigits:0,maximumFractionDigits:d}):'—';
const LABELS={usd_egp_mid:'الدولار',gold_egp_oz:'الذهب',silver_egp_oz:'الفضة',egx30_close:'EGX30',spy_egp:'S&P 500',qqq_egp:'ناسداك 100',btc_egp:'بيتكوين'};
const COLORS=window.KHATER_THEME?.series||{};
let snapshot=null,powerChart=null,assetChart=null,powerSeries=null,assetSeries={},activeAssetKey=null;
function sorted(rows){return (rows||[]).filter(r=>Number.isFinite(Number(r.value))&&r.date).slice().sort((a,b)=>String(a.date).localeCompare(String(b.date)));}
function yearly(rows){const out=[];for(const r of sorted(rows)){const year=String(r.date).slice(0,4),last=out.at(-1);if(!last||last.year!==year)out.push({year,value:Number(r.value),date:r.date});else{last.value=Number(r.value);last.date=r.date;}}return out;}
function chartLayout(){const base=window.KHATER_THEME?.chartLayout?.()||{};const color=window.KHATER_THEME?.color||{};return{...base,background:{color:color.surface||'#fff'},textColor:color.ink||'#0e2327',fontSize:13,fontFamily:window.KHATER_THEME?.font?.chart||'Cairo, sans-serif',attributionLogo:false};}
function chartGrid(){const grid=window.KHATER_THEME?.chartGrid?.()||{};return{vertLines:{...(grid.vertLines||{}),color:'#e1e8e6'},horzLines:{...(grid.horzLines||{}),color:'#dfe7e5'}};}
function chartColors(){const color=window.KHATER_THEME?.color||{};return{border:color.borderStrong||color.border||'#c7d4d1',ink:color.ink||'#0e2327',muted:color.muted||'#52686b',primary:color.chartPrimary||'#087f63'};}
function commonChartOptions(colors){return{layout:chartLayout(),grid:chartGrid(),rightPriceScale:{borderColor:colors.border,scaleMargins:{top:.08,bottom:.08},minimumWidth:72},timeScale:{borderColor:colors.border,rightOffset:4,barSpacing:8,minBarSpacing:3},localization:{locale:'en-US'},crosshair:{mode:LightweightCharts.CrosshairMode.Normal,vertLine:{color:'rgba(8,127,99,.28)',width:1,style:2,labelBackgroundColor:colors.primary},horzLine:{color:'rgba(8,127,99,.28)',width:1,style:2,labelBackgroundColor:colors.primary}}};}
function renderHero(){const points=yearly(snapshot.money?.[0]?.rows),latest=points.at(-1),loss=latest?100-latest.value:null;$('hero-value').textContent=latest?`${fmt(latest.value)} جنيه`:'—';$('hero-loss').textContent=latest?`تآكل ${fmt(loss)}% من القوة الشرائية`:'غير متاح';$('hero-date').textContent=latest?`آخر قراءة: ${latest.year}`:'—';$('power-summary').textContent=latest?`من 100 جنيه عند بداية السلسلة، بقيت قوة شرائية تعادل ${fmt(latest.value)} جنيه وفق التضخم الشهري الفعلي المسجل في قاعدة البيانات.`:'لا تتوفر قراءة كافية.';}
function setupPowerChart(){const el=$('power-chart'),colors=chartColors();powerChart=LightweightCharts.createChart(el,{...commonChartOptions(colors),handleScroll:false,handleScale:false});powerSeries=powerChart.addLineSeries({color:COLORS.purchasing||colors.primary,lineWidth:3,title:'القوة الشرائية',priceLineVisible:false,lastValueVisible:true,crosshairMarkerVisible:true,crosshairMarkerRadius:4});const rows=sorted(snapshot.money?.[0]?.rows);powerSeries.setData(rows.map(r=>({time:r.date,value:Number(r.value)})));powerSeries.createPriceLine({price:100,color:'#8a9695',lineWidth:1,lineStyle:2,axisLabelVisible:true,title:'100'});powerChart.timeScale().fitContent();powerChart.subscribeCrosshairMove(param=>{const tip=$('power-tip');if(!tip||!param.time){if(tip)tip.hidden=true;return;}const value=param.seriesData.get(powerSeries)?.value;if(value==null){tip.hidden=true;return;}tip.innerHTML=`<strong>${String(param.time).slice(0,4)}</strong><span>القوة الشرائية: ${fmt(value)} جنيه</span><em>التآكل: ${fmt(100-value)}%</em>`;tip.hidden=false;});new ResizeObserver(()=>powerChart.resize(el.clientWidth,el.clientHeight)).observe(el);}
function renderYearStrip(){const root=$('year-strip'),points=yearly(snapshot.money?.[0]?.rows);root.innerHTML=points.map(p=>`<button type="button" class="year-point" data-date="${esc(p.date)}"><span>${p.year}</span><strong>${fmt(p.value)}</strong><small>${fmt(100-p.value)}% تآكل</small></button>`).join('');root.addEventListener('click',e=>{const b=e.target.closest('.year-point');if(!b)return;const point=points.find(p=>p.date===b.dataset.date);if(!point)return;powerChart.timeScale().setVisibleRange({from:point.date,to:point.date});root.querySelectorAll('.year-point').forEach(x=>x.classList.toggle('is-selected',x===b));});}
function renderAssetTabs(assets){const root=$('asset-tabs');if(!root)return;const available=assets.filter(item=>assetSeries[item.key]);root.innerHTML=available.map((item,index)=>{const active=index===0;return `<button type="button" role="tab" class="asset-tab${active?' is-active':''}" data-key="${esc(item.key)}" aria-selected="${active}" tabindex="${active?'0':'-1'}"><i style="background:${esc(COLORS[item.key]||'#087f63')}"></i><span>${esc(LABELS[item.key]||item.label)}</span></button>`;}).join('');root.addEventListener('click',e=>{const button=e.target.closest('.asset-tab');if(!button)return;selectAsset(button.dataset.key);});root.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const tabs=[...root.querySelectorAll('.asset-tab')],current=tabs.indexOf(document.activeElement);let next=current;if(e.key==='ArrowLeft')next=current<=0?tabs.length-1:current-1;if(e.key==='ArrowRight')next=current>=tabs.length-1?0:current+1;if(e.key==='Home')next=0;if(e.key==='End')next=tabs.length-1;tabs[next]?.focus();tabs[next]?.click();});if(available[0])selectAsset(available[0].key);}
function selectAsset(key){const series=assetSeries[key];if(!series)return;activeAssetKey=key;Object.entries(assetSeries).forEach(([itemKey,itemSeries])=>itemSeries.applyOptions({visible:itemKey===key,lastValueVisible:itemKey===key}));document.querySelectorAll('.asset-tab').forEach(button=>{const active=button.dataset.key===key;button.classList.toggle('is-active',active);button.setAttribute('aria-selected',String(active));button.tabIndex=active?0:-1;});const item=(snapshot.assets||[]).find(x=>x.key===key);const label=LABELS[key]||item?.label||key;$('asset-selected-label').textContent=label;$('asset-chart').setAttribute('aria-label',`مسار ${label} معاد تأسيسه عند 100`);$('asset-tip').hidden=true;assetChart?.timeScale().fitContent();}
function setupAssetChart(){const el=$('asset-chart'),colors=chartColors();assetChart=LightweightCharts.createChart(el,{...commonChartOptions(colors),handleScroll:true,handleScale:true});assetSeries={};const assets=snapshot.assets||[];assets.forEach(item=>{const data=sorted(item.rows).map(r=>({time:r.date,value:Number(r.value)}));if(!data.length)return;const series=assetChart.addLineSeries({color:COLORS[item.key]||colors.primary,lineWidth:2.5,title:item.label,priceLineVisible:false,lastValueVisible:false,crosshairMarkerVisible:true,crosshairMarkerRadius:4});series.setData(data);series.applyOptions({visible:false});assetSeries[item.key]=series;});renderAssetTabs(assets);assetChart.subscribeCrosshairMove(param=>{const tip=$('asset-tip');if(!tip||!param.time||!activeAssetKey){if(tip)tip.hidden=true;return;}const series=assetSeries[activeAssetKey],value=param.seriesData.get(series)?.value;if(value==null){tip.hidden=true;return;}const item=(snapshot.assets||[]).find(x=>x.key===activeAssetKey);const label=LABELS[activeAssetKey]||item?.label||activeAssetKey;tip.innerHTML=`<small>${esc(String(param.time))}</small><div><span>${esc(label)}</span><strong>${fmt(value)}</strong></div><em>مقارنة تبدأ من 100</em>`;tip.hidden=false;});new ResizeObserver(()=>assetChart.resize(el.clientWidth,el.clientHeight)).observe(el);}
function renderContext(){const map=[['التضخم العام','cpi_headline_mom_pct','% شهري',2],['الدولار / الجنيه','usd_egp_mid','جنيه لكل دولار',2],['الذهب / الجنيه','gold_egp_oz','جنيه للأونصة',0],['EGX30','egx30_close','نقطة',1],['أذون 91 يومًا','tbill_91_avg_yield_pct','% سنوي',2]];const lookup=Object.fromEntries((snapshot.rates||[]).map(x=>[x.key,x])),assetLookup=Object.fromEntries((snapshot.assets||[]).map(x=>[x.key,x]));$('context-grid').innerHTML=map.map(([label,key,unit,d])=>{const item=lookup[key]||assetLookup[key],row=item?.rows?.at(-1);return `<article><span>${label}</span><strong>${row?fmt(row.value,d):'—'}</strong><small>${unit} · ${row?.date||'—'}</small></article>`;}).join('');}
window.addEventListener('DOMContentLoaded',async()=>{try{snapshot=await window.KHATER_DATA.wealth.snapshot();renderHero();setupPowerChart();renderYearStrip();setupAssetChart();renderContext();}catch(error){console.error('[wealth-page]',error);const main=$('main-content');if(main)main.innerHTML='<div class="error-state">تعذر قراءة البيانات الفعلية من طبقة البيانات. لم يتم عرض أرقام بديلة.</div>';}});
