-- Remove history rows that were generated by the old
-- fallback_updated_at_when_as_of_date_null trigger.
-- Only rows for currently undated official NAVs, from the same source,
-- and on/after 2026-09-07 are removed. Other-source history is preserved.
delete from public.fund_price_history h
using public.nav_official n
where h.fund_id = n.fund_id
  and n.as_of_date is null
  and h.source_id = n.source_id
  and h.as_of_date >= date '2026-09-07';
